all:
  hosts:
    node0:
      ansible_host: 192.168.122.8
      ip: 192.168.122.8
      access_ip: 192.168.122.8
      ansible_user: root
    node1:
      ansible_host: 192.168.122.194
      ip: 192.168.122.194
      access_ip: 192.168.122.194
      ansible_user: root
    node2:
      ansible_host: 192.168.122.177
      ip: 192.168.122.177
      access_ip: 192.168.122.177
      ansible_user: root
  children:
    kube-master:
      hosts:
        node0:
    kube-node:
      hosts:
        # node0:
        node1:
        node2:
    etcd:
      hosts:
        node0:
        node1:
        node2:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
